### ISSUE TITLE
I think version 1.19.1 was uploaded over 1.19

### ISSUE THREAD

**Issue by hopeimhelpful** [Snownee/Companion#11]
### Mod loader

Forge

### Minecraft version

1.19

### Mod version

3.0.2

### Modloader version

Forge: 41.1.0

### If bug:

- [ ] Can you reproduce this issue with relevant mods only?

### Issue description

I have not looked very far into it except that it downloads 1.19.1 on both the forge client and the website.  I do not know what github is really, just throwing together some mods for the fun of it.

**Comment by Snownee** [comment]
fixed
