### ISSUE TITLE
Can this mod run on arclight server(1.18.2) ?

### ISSUE THREAD

**Issue by MossCG** [Snownee/Companion#14]
### Mod loader

Forge

### Minecraft version

1.18.2

### Mod version

2.2.0

### Modloader version

Forge 40.1.87

### If bug:

- [X] Can you reproduce this issue with relevant mods only?

### If bug: The latest.log file

https://pastebin.com/KEzy9Vrp

### Issue description

I add this mod on my server , using arclight(https://github.com/IzzelAliz/Arclight) as my server core.
But it crashed.

**Comment by Snownee** [comment]
I doubt it can work with Arclight. There is hard mixin conflict with their `ServerPlayerMixin`. I don't know much about mixin but I don't think I can mixin into an overwritten method? Maybe you can ask their dev.
