### ISSUE TITLE
Server is crashing

### ISSUE THREAD

**Issue by sternschnaube** [Snownee/Companion#17]
### Mod loader

Fabric

### Minecraft version

1.19.3

### Mod version

4.1.0

### Modloader version

0.14.12

### If bug:

- [ ] Can you reproduce this issue with relevant mods only?

### If bug: The latest.log file

https://pastebin.com/raw/Dd2NfVD9

### Issue description

Hello, I can connect to the server - after 5-10 seconds the server shuts down.

**Comment by venaminecraft** [comment]
Everything works now - thanks 😊
