### ISSUE TITLE
Idea: "Wandering" mode for all pets

### ISSUE THREAD

**Issue by FumpleWumper** [Snownee/Companion#18]
### Mod loader

Fabric

### Minecraft version

1.19.2

### Mod version

3.2.1

### Modloader version

Fabric 1.14.2 + API 0.72.0

### If bug:

- [ ] Can you reproduce this issue with relevant mods only?

### Issue description

I already practically use this mod on every pack that I make cuz of all of its uses, so I'd like to suggest another one to be added that would be really helpful:

Just like how you can make pets sit or follow, add a "wandering" option to make them walk around the area you left them in!

I like hoarding a bunch of pets, so much so that I usually build a space just for them to be in while I go somewhere dangerous I don't want them to follow me into, but I always feel bad when they sit in place instead of going around the room I made specifically for them. Alex Mobs already has this option for most of its tameable animals, but I play on Fabric where that mod doesn't exist, and there's not any mods to my knowledge that add this option to the dogs, cats, and parrots, so this would be really nice if you could add it!

Thanks for reading and keep up the awesome work <3

**Comment by Snownee** [comment]
You can try this one: https://www.curseforge.com/minecraft/mc-mods/indypets

**Comment by FumpleWumper** [comment]
Ah that looks great, thank you :D
