### ISSUE TITLE
Horse teleports into buildings when unloading

### ISSUE THREAD

**Issue by RandomGgames** [Snownee/Companion#20]
### Mod loader

Fabric

### Minecraft version

1.19.2

### Mod version

3.2.1

### Modloader version

Fabric 0.14.4

### If bug:

- [x] Can you reproduce this issue with relevant mods only?

### Issue description

A horse tamed by you will teleport to you before it unloads. Add toggle option so it doesn't teleport into a house or underground base. Also makes this incompatible with the horse buff mod where horses will not wonder. I've also noticed this happening even if the horse is leashed to a fence,

**Comment by Cape-City** [comment]
Nearly the same here - i noticed it first when entering the nether and thought "What the heck is my horse doin' here?" :D
When traveling in the overworld, far far away from my base, the horse did'nt teleport to me.
