### ISSUE TITLE
Tamed horses, mules and donkeys keep teleporting to me even when leashed to a fence.

### ISSUE THREAD

**Issue by spicylambliver** [Snownee/Companion#21]
### Mod loader

Forge

### Minecraft version

19.2

### Mod version

3.1.2

### Modloader version

43.1.52

### If bug:

- [ ] Can you reproduce this issue with relevant mods only?

### Issue description

Tamed horses, mules and donkeys keep teleporting to me at random times even if I leashed them to a fence. One of then teleported to the End with me somehow, after I traveled to the End Portal without it, and it almost died. I'm unsure what to do, I looked into the cloth config but I can't tell which option would make them stop doing that. Especially since I enjoy my pets teleporting to me once they fail to follow me (although except for when my cats go crazy looking for a bed or chest I haven't had a problem with that). 
I hope this is the right place to ask for help, but if not I will delete this post. Please help ;-;
[latest.log](https://github.com/Snownee/Companion/files/11181456/latest.log)
I'm unsure whether my log will be useful but I attached it just in case. Thank you in advance!

**Comment by RandomGgames** [comment]
Probably related to my issue https://github.com/Snownee/Companion/issues/20
