### ISSUE TITLE
Library Required

### ISSUE THREAD

**Issue by JulJuls** [Snownee/Companion#3]
### Mod loader

Forge

### Minecraft version

1.18.1

### Mod version

All

### Modloader version

Forge

### If bug:

- [ ] Can you reproduce this issue with relevant mods only?

### Issue description

Please, specify somewhere into your forge page that Kiwi Library is needed.
My game couldn't start and I wandered a lot to understand a required library was missing (after a lot I got the message "you are missing kiwi"). Thank you

EDIT: I saw there is something into the dependancies, but usually there are added add-on mods, I suggest you to write it down into the description too.
Oh and now that I added the library and I could try it, I would like to thank you for the mod, it's so useful T^T

**Comment by Snownee** [comment]
you should request Forge team to add better information about missing requirements instead
