### ISSUE TITLE
Missing license

### ISSUE THREAD

**Issue by YoshiRulz** [Snownee/Companion#30]
If this mod is intended to be proprietary, please add a `license.md` explaining what people are permitted to do with it.
And if not, I suggest applying the [GNU AGPL](https://choosealicense.com/licenses/agpl-3.0/), which requires anyone who redistributes your mod to also include the source (such as by linking to the repo), and protects both you and users from certain legal traps.

**Comment by Snownee** [comment]
This project is ARR. and:

> Typically, when a copyleft license is wanted, the [GPL-3.0](https://flight.beehiiv.net/v2/clicks/eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1cmwiOiJodHRwczovL3NwZHgub3JnL2xpY2Vuc2VzL0dQTC0zLjAtb25seS5odG1sP3V0bV9zb3VyY2U9YmxvZy5tb2RyaW50aC5jb20mdXRtX21lZGl1bT1yZWZlcnJhbCZ1dG1fY2FtcGFpZ249YmVnaW5uZXItcy1ndWlkZS10by1saWNlbnNpbmcteW91ci1tb2RzIiwicG9zdF9pZCI6IjFkMDY5ZjJmLWZjOGQtNDI0Zi05YzkwLTQ3NmU3ZjY2ZDgwOCIsInB1YmxpY2F0aW9uX2lkIjoiYTQ5ZjhlMWItMzgzNS00ZWExLWE4NWItMTE4YzY0MjVlYmMzIiwidmlzaXRfdG9rZW4iOiI1ZjQzNmRmZC03NzI4LTQ0YjctOGI5Ni1jNzAwMGVhZWE2MzciLCJpYXQiOjE3MDcwNzQ1ODYsImlzcyI6Im9yY2hpZCJ9.DCtw5L6jo9vyrq-9eTwRZl4LVkyV6ILrKtKaBhuHEU8) or [AGPL-3.0](https://flight.beehiiv.net/v2/clicks/eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1cmwiOiJodHRwczovL3NwZHgub3JnL2xpY2Vuc2VzL0FHUEwtMy4wLW9ubHkuaHRtbD91dG1fc291cmNlPWJsb2cubW9kcmludGguY29tJnV0bV9tZWRpdW09cmVmZXJyYWwmdXRtX2NhbXBhaWduPWJlZ2lubmVyLXMtZ3VpZGUtdG8tbGljZW5zaW5nLXlvdXItbW9kcyIsInBvc3RfaWQiOiIxZDA2OWYyZi1mYzhkLTQyNGYtOWM5MC00NzZlN2Y2NmQ4MDgiLCJwdWJsaWNhdGlvbl9pZCI6ImE0OWY4ZTFiLTM4MzUtNGVhMS1hODViLTExOGM2NDI1ZWJjMyIsInZpc2l0X3Rva2VuIjoiNWY0MzZkZmQtNzcyOC00NGI3LThiOTYtYzcwMDBlYWVhNjM3IiwiaWF0IjoxNzA3MDc0NTg2LCJpc3MiOiJvcmNoaWQifQ.Zx43iEslRDb4qDpn671n36iyQpkoKJ13Jww651FVyVA) would be used. However, these licenses are incompatible if linking into Minecraft, due to an issue with the [difference between proprietary and free software](https://flight.beehiiv.net/v2/clicks/eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1cmwiOiJodHRwczovL3d3dy5nbnUub3JnL2xpY2Vuc2VzL2dwbC1mYXEuaHRtbD91dG1fc291cmNlPWJsb2cubW9kcmludGguY29tJnV0bV9tZWRpdW09cmVmZXJyYWwmdXRtX2NhbXBhaWduPWJlZ2lubmVyLXMtZ3VpZGUtdG8tbGljZW5zaW5nLXlvdXItbW9kcyNHUExQbHVnaW5zIiwicG9zdF9pZCI6IjFkMDY5ZjJmLWZjOGQtNDI0Zi05YzkwLTQ3NmU3ZjY2ZDgwOCIsInB1YmxpY2F0aW9uX2lkIjoiYTQ5ZjhlMWItMzgzNS00ZWExLWE4NWItMTE4YzY0MjVlYmMzIiwidmlzaXRfdG9rZW4iOiI1ZjQzNmRmZC03NzI4LTQ0YjctOGI5Ni1jNzAwMGVhZWE2MzciLCJpYXQiOjE3MDcwNzQ1ODYsImlzcyI6Im9yY2hpZCJ9._55drYCdDc1c5X_t1gJka0Q4RIwrCRcPNaqwTpZxOPc) outlined by these licenses.

https://blog.modrinth.com/p/licensing-guide
