### ISSUE TITLE
[Crash]; Random Crash

### ISSUE THREAD

**Issue by Fyoncle** [Snownee/Companion#36]
### Mod loader

Fabric

### Minecraft version

1.20.1

### Mod version

5.2.2

### Modloader version

0.16.5

### If bug:

- [ ] Can you reproduce this issue with relevant mods only?

### If bug: The latest.log file

https://mclo.gs/9skVYGp

**Comment by Fyoncle** [comment]
This could be related to the mod called "Wakes" too, but i saw companion related stuff in the crash report so wanted to ask.

**Comment by Snownee** [comment]
unrelated to Companion

**Comment by Fyoncle** [comment]
> unrelated to Companion

Great thanks! ❤️
