### ISSUE TITLE
Incompatibly with Alexs Mobs 

### ISSUE THREAD

**Issue by DaddySpin** [Snownee/Companion#4]
### Mod loader

Forge

### Minecraft version

1.18.1

### Mod version

1.1.1

### Modloader version

39.0.66

### If bug:

- [ ] Can you reproduce this issue with relevant mods only?

### Issue description

Alexs Mobs has a few mobs that you can tame that do not follow you and can't be told to stay, so the force teleport features are causing creatures that don't follow you to have weird behavior.

A simple solution would be for you to add a blacklist for the teleport feature.

**Comment by Snownee** [comment]
what mobs?

**Comment by DaddySpin** [comment]
I haven't played that long, but the ones I know of are crocodiles and elephants.

**Comment by Snownee** [comment]
How do you tame a crocodile?

**Comment by Snownee** [comment]
nevermind

**Comment by SHXRKIEgg** [comment]
Hi has this been added to the mod yet as their is still some issues with Alex Mobs?
https://github.com/LunaPixelStudios/Better-Minecraft/issues/162

**Comment by Snownee** [comment]
@SharkieTV I suppose it has been fixed

**Comment by Snownee** [comment]
@SharkieTV also here it restricts that sitting animals will not be affected

https://github.com/Snownee/Companion/blob/1.18-forge/src/main/java/snownee/companion/Hooks.java#L183
