### ISSUE TITLE
Update to 1.19 please:)

### ISSUE THREAD

**Issue by ghost** [Snownee/Companion#7]
### Mod loader

Fabric

### Minecraft version

1.19

### Mod version

2.0.1

### Modloader version

0.14.8

### If bug:

- [ ] Can you reproduce this issue with relevant mods only?

**Comment by chimericdream** [comment]
I just tested this with 1.19, and everything _seems_ to work as expected. Because the compatibility in the `fabric.mod.json` is set as `>=1.18.2`, I didn't even need to make any config changes to force compatibility. @Snownee perhaps you simply need to mark it as compatible in CurseForge?

**Comment by ghost** [comment]
Hello @chimericdream , thank you! The mod alone loads fine, but when I try to install Kiwi aside my game crashes.
I think Kiwi needs to be updated. 

I have two questions @Snownee.
There is no config file, right - I need strictly Kiwi to make changes?
Can this mod be used server-side? I would love that.

**Comment by Snownee** [comment]
You can run it on 1.19, but I am not sure if it will be stable.

Currently it can be server-side. No guarantee of the future.

**Comment by ghost** [comment]
Thank you, that's awesome, I hope it keeps still server-side in the future 🥰
