### ISSUE TITLE
1.19.0 Support

### ISSUE THREAD

**Issue by mimi-min** [Snownee/Companion#9]
### Mod loader

Forge

### Minecraft version

1.19

### Mod version

None

### Modloader version

Forge 41.1.0

### If bug:

- [ ] Can you reproduce this issue with relevant mods only?

### Issue description

My server complains if I try to install mods marked as 1.19.1 on it, currently I don't see one specifically for 1.19 so if you could add it, that would be fantastic!

Thank you <3

**Comment by Snownee** [comment]
complain what?

**Comment by mimi-min** [comment]
Ah, I mean in the console it says that the Minecraft version is incompatible with the mods.

**Comment by Snownee** [comment]
https://www.curseforge.com/minecraft/mc-mods/companion/files/3929186

**Comment by Snownee** [comment]
https://www.curseforge.com/minecraft/mc-mods/companion/files/3929325

**Comment by Snownee** [comment]
https://www.curseforge.com/minecraft/mc-mods/companion/files/3929404
